name: speedometer_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:

  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  geolocator: ^14.0.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.8
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  user_repository:
    path: packages/user_repository
  google_sign_in: ^7.2.0
  lock_orientation_screen: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/